# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

report: "report/workflow.rst"

include: "rules/common.smk"


rule all:
    input:
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.
        expand(["results/cellranger_count/{sample}/outs/raw_feature_bc_matrix.h5",
                "results/cellranger_count/{sample}/outs/filtered_feature_bc_matrix.h5",
                "results/cellranger_count/{sample}/outs/possorted_genome_bam.bam"],
               sample=samples['sample'])


include: "rules/cellranger.smk"
include: "rules/other.smk"
